name: Deploy (PM2)
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.SERVER_PATH }}  # e.g., /var/www/stickers
          git fetch --all
          git checkout main
          git pull --ff-only origin main
          git reset --hard origin/main
          git clean -fd
          export NODE_ENV=production
          npm ci --omit=dev
          # now we'll build the vite files on the server, must include=dev since vite is dev dep
          cd client
          npm ci --include=dev
          npm run build
          # now we'll copy the client/dist vite files to our public /var/www/stickerboards that nginx serves
          rsync -a --delete /root/apps/stickers/client/dist/ /var/www/stickerboards/
          cd ..
          sudo nginx -t && sudo systemctl reload nginx
          pm2 reload stickers || pm2 start server.js --name stickers
          pm2 save
          EOF
